export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

// USER AUTHENTICATION
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

// MANAGER PERMISSION
export const TOGGLE_MANAGER_PERMISSION = 'TOGGLE_MANAGER_PERMISSION';
export const MANAGER_NOW = 'MANAGER_NOW';
export const MANAGER_TAKEN = 'MANAGER_TAKEN';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
// GROUP
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';
export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_NAME_SUCCESS = 'GET_GROUP_NAME_SUCCESS';
export const CLEAR_GROUP = 'CLEAR_GROUP';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const LEAVE_GROUP = 'LEAVE_GROUP';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const REMOVE_GROUP_SUCCESS = 'REMOVE_GROUP_SUCCESS';
export const GET_GROUP_DATA_SUCCESS = 'GET_GROUP_DATA_SUCCESS';
export const GET_MEETING_TIME_SUCCESS = 'GET_MEETING_TIME_SUCCESS';

// USER DATA
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const CHECK_MANAGER_SUCCESS = 'CHECK_MANAGER_SUCCESS';

// MESSAGE
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';

